import json
import os

batch_file = "/Users/fabiopereira/Desktop/desafio-fotos/scratch/batches/batch_3.json"
out_dir = "/Users/fabiopereira/Desktop/desafio-fotos/outputs/cards-enriquecidos"
os.makedirs(out_dir, exist_ok=True)

with open(batch_file, "r", encoding="utf-8") as f:
    cards = json.load(f)

# Manually mapped answers and explanations
data = {
    "031": {
        "correct": "C",
        "trans_q": "Cenário: Geração de Código com Claude Code\nVocê está usando o Claude Code para acelerar o desenvolvimento de software. Sua equipe o usa para geração de código, refatoração, depuração e documentação. Você precisa integrá-lo ao seu fluxo de trabalho de desenvolvimento com comandos slash customizados, configurações CLAUDE.md e entender quando usar o plan mode vs execução direta. Seu comando /migrate-to-new-logger usa um coordenador que lança subagentes para escanear pacotes e propor edições. Em uma simulação (dry run), o plano final diz que o logger legado aparece apenas em billing e notifications. Mais tarde, revisores descobrem que o pacote auth nunca foi escaneado porque um subagente encontrou um erro de permissão de caminho, enquanto o subagente de busca para reporting escaneou com sucesso e não encontrou correspondências. O coordenador recebeu ambos os resultados como \"nenhuma descoberta\". Qual mudança melhoraria mais a confiabilidade de futuros planos de migração?",
        "tech_exp": "A pergunta testa o tratamento de erros e a distinção de sinais em sistemas multi-agentes.\n\nPor que a alternativa C é a correta:\nO coordenador precisa distinguir entre uma ausência verdadeira de resultados (busca bem-sucedida, nada encontrado) e uma falha de execução (erro de permissão, busca não realizada). Ao forçar os subagentes a reportarem explicitamente falhas de acesso separadas de buscas vazias, o coordenador pode tomar decisões corretas (como alertar o usuário, tentar outro caminho ou escalar) em vez de silenciosamente omitir pacotes críticos. Isso evita os falsos negativos perigosos que o cenário descreve.\n\nPor que as outras estão erradas:\n\nA) Tratar erros silenciosos como sucesso é um anti-pattern grave de resiliência, delegando a responsabilidade para os humanos e derrotando o propósito da automação.\nB) Terminar todo o fluxo de trabalho por causa de uma falha em um pacote é frágil e desperdiça trabalho útil (fail-fast excessivo em um processo em lote).\nD) Resumos em linguagem natural forçam o coordenador a adivinhar o status (parsing frágil), em vez de usar um contrato claro entre subagente e coordenador.\n\nDica importante:\nUm padrão recorrente é o 'Fail Noisily' ou 'Explicit Error Handling'. Em sistemas de agentes, nunca oculte falhas técnicas sob retornos semânticos vazios. Os estados de erro devem ser passados como dados estruturados para a camada de orquestração.",
        "child_exp": "A missão do carteiro 📬\nImagine um carteiro que tem que entregar cartas em duas casas. Em uma casa não tinha ninguém, e na outra o portão estava trancado e ele nem conseguiu entrar. Ele volta e diz pro chefe: \"Não entreguei nada nas duas\". O chefe acha que as duas estavam vazias!\n\nPor que a alternativa C é a correta:\nPara não ter confusão, o carteiro precisa explicar direito: \"Na primeira casa não tinha ninguém (busca vazia), mas na segunda eu nem consegui entrar (erro de acesso)\". Assim o chefe sabe que precisa dar a chave do portão para ele tentar de novo.\n\nPor que as outras estão erradas:\n\nA) Fingir que está tudo bem e deixar o chefe descobrir sozinho é uma péssima ideia.\nB) Desistir de entregar cartas na cidade toda só porque um portão estava trancado é um exagero!\nD) Contar uma história comprida e confusa em vez de só falar \"Portão trancado\" ou \"Casa vazia\" só atrapalha o chefe a entender rápido.\n\nDica importante:\nSempre separe \"eu procurei e não achei\" de \"eu nem consegui procurar\". Na programação, isso evita que a gente perca coisas importantes sem perceber!",
        "opt_trans": {
            "A": "Tratar cada resultado de subagente sem referências de código como bem-sucedido, e então depender dos revisores para pegar quaisquer pacotes faltando.",
            "B": "Terminar todo o fluxo de trabalho de migração sempre que qualquer escaneamento de pacote falhar, descartando descobertas bem-sucedidas de outros subagentes.",
            "C": "Fazer com que os subagentes relatem buscas vazias bem-sucedidas separadamente de falhas de acesso, incluindo caminhos tentados, consultas, resultados parciais e próximos passos sugeridos.",
            "D": "Pedir a cada subagente para resumir as falhas em linguagem natural, permitindo que o coordenador infira se descobertas ausentes indicam código limpo."
        }
    },
    "032": {
        "correct": "D",
        "trans_q": "Cenário: Agente de Resolução de Suporte ao Cliente\nVocê está construindo um agente de resolução de suporte ao cliente usando o Claude Agent SDK. O agente lida com solicitações de alta ambiguidade, como devoluções, disputas de cobrança e problemas de conta. Ele tem acesso a sistemas de backend através de ferramentas MCP (get_customer, lookup_order, process_refund, escalate_to_human). Sua meta é de 80%+ de resolução no primeiro contato, sabendo quando escalar. Logs de produção mostram seleção inconsistente de ferramentas para mensagens relacionadas a cobrança. Solicitações de reembolso de rotina às vezes são escaladas, enquanto solicitações que requerem revisão de política às vezes são enviadas diretamente para process_refund. Não há erros de backend, e o registro de ferramentas mostra descrições amplas com poucos detalhes sobre efeitos colaterais, entradas elegíveis ou limites entre o tratamento de reembolso e escalonamento humano. Qual é a melhor primeira mudança para melhorar a confiabilidade?",
        "tech_exp": "A pergunta foca na engenharia de prompt para descrições de ferramentas (Tool Descriptions) em chamadas de função.\n\nPor que a alternativa D é a correta:\nModelos de linguagem tomam decisões de roteamento baseados inteiramente nas descrições das ferramentas. Se a descrição for muito ampla e não tiver limites claros (boundaries), o modelo irá alucinar o caso de uso. Reescrever as descrições detalhando exatamente quando usar uma vs a outra (ex: 'use para reembolso abaixo de $50' vs 'use se a política exigir revisão') é a forma mais direta e arquiteturalmente correta de consertar o comportamento não determinístico, dando grounding para a decisão.\n\nPor que as outras estão erradas:\n\nA) Roteadores por palavras-chave são frágeis e quebram a flexibilidade do agente (ex: 'quero falar com o supervisor sobre meu refund' ativaria qual?).\nB) Aumentar a temperatura apenas introduzirá mais aleatoriedade e inconsistência, piorando a situação de decisões incorretas.\nC) Fazer merge das ferramentas cria um 'God Tool' com lógica excessivamente complexa, prejudicando o princípio da responsabilidade única e ocultando a intenção do agente.\n\nDica importante:\nDescrições de ferramentas não são apenas comentários de código, são o 'prompt' principal para a tomada de decisão. Elas devem conter restrições explícitas, exemplos de uso e fronteiras claras com outras ferramentas (Tool Boundary Pattern).",
        "child_exp": "A missão do ajudante de loja 🏪\nImagine um ajudante de loja que tem duas caixas: uma diz \"Devolver dinheiro\" e a outra diz \"Chamar o gerente\". Se você não explicar direito quando usar cada uma, ele vai ficar confuso e chamar o gerente para coisas bobas ou tentar devolver dinheiro que não devia.\n\nPor que a alternativa D é a correta:\nA melhor coisa a fazer é colar uma etiqueta com regras super claras nas caixas! \"Use essa só se o produto custar menos de 50 reais. Se for mais caro, use a outra\". Assim ele sabe exatamente o que fazer sem ter que adivinhar.\n\nPor que as outras estão erradas:\n\nA) Tentar adivinhar a caixa só porque o cliente falou uma palavra solta (como \"gerente\") pode dar muito errado se a frase inteira for diferente.\nB) Dizer para o ajudante \"seja criativo e tente coisas aleatórias\" vai deixar a loja uma bagunça completa!\nC) Juntar as duas caixas em uma caixa mágica gigante só esconde o problema e deixa o trabalho muito mais complicado por dentro.\n\nDica importante:\nSempre explique as regras do jogo claramente. Se as ferramentas têm nomes e descrições confusas, o robô também vai ficar confuso!",
        "opt_trans": {
            "A": "Adicionar um roteador de palavras-chave que envia mensagens contendo refund para process_refund e mensagens contendo supervisor para escalate_to_human.",
            "B": "Aumentar levemente a temperatura para que o agente explore opções alternativas de ferramentas em vez de repetir a mesma ação de cobrança.",
            "C": "Mesclar process_refund e escalate_to_human em uma ferramenta handle_billing_case que decide internamente a ação correta de backend.",
            "D": "Reescrever as descrições das ferramentas afetadas para especificar propósitos, entradas necessárias, efeitos colaterais, exemplos e limites entre fluxos de reembolso e escalonamento."
        }
    },
    "033": {
        "correct": "B",
        "trans_q": "Cenário: Agente de Resolução de Suporte ao Cliente\nVocê está construindo um agente de suporte. O agente lida com solicitações de alta ambiguidade. Ele tem acesso a sistemas backend através de ferramentas MCP. Durante os testes, quando um cliente fornece detalhes de identificação suficientes mas pergunta \"Você pode apenas checar isso?\", o agente às vezes responde com orientações genéricas em vez de usar qualquer ferramenta de backend. Você não sabe com antecedência qual ferramenta é apropriada, mas toda resposta de produção deve ser fundamentada em pelo menos uma ação de backend. Qual configuração aborda melhor esse comportamento?",
        "tech_exp": "Esta pergunta foca em como forçar o uso de ferramentas (Tool Choice) no Claude Agent SDK/API.\n\nPor que a alternativa B é a correta:\nAo configurar `tool_choice` como `any`, você instrui a API a rejeitar respostas que não incluam pelo menos uma chamada de ferramenta. O Claude será forçado a escolher uma ferramenta da lista disponível baseada no contexto, resolvendo o problema de respostas puramente conversacionais/genéricas sem perder a autonomia de decidir *qual* ferramenta chamar. Essa é a configuração exata para quando uma ação é obrigatória, mas a seleção específica depende da inteligência do modelo.\n\nPor que as outras estão erradas:\n\nA) Forçar uma ferramenta específica (`tool_choice: {type: 'tool', name: 'get_customer'}`) tira do modelo a capacidade de ir direto para outra ferramenta se for mais apropriado.\nC) Fazer retry (looping) com base em correspondência de frases (phrase matching) é uma solução reativa (gambiarras) e ineficiente, gastando tokens e tempo desnecessariamente.\nD) Apenas fortalecer o prompt do sistema mantendo o modo `auto` não garante deterministicamente que o modelo nunca pulará o uso de ferramentas; ele ainda pode alucinar ou ignorar a instrução, enquanto o parâmetro na API é uma garantia estrita.\n\nDica importante:\nOs parâmetros de `tool_choice` (auto, any, tool) são cruciais. Use `any` quando quiser garantir que o LLM execute alguma ação (grounding obrigatório) sem ditar qual ferramenta específica usar.",
        "child_exp": "A missão do detetive 🕵️\nImagine um detetive que, de vez em quando, tenta resolver um mistério só adivinhando, sem usar a lupa ou o pó de digitais. A regra agora é: ele PRECISA investigar de verdade toda vez que alguém pedir ajuda.\n\nPor que a alternativa B é a correta:\nA gente muda a regra do jogo para: \"Você é OBRIGADO a usar pelo menos uma ferramenta da sua maleta (tool_choice = any)\". Ele ainda pode escolher se vai usar a lupa ou o pozinho, mas ele não pode mais só dar uma resposta inventada da cabeça dele sem usar nada.\n\nPor que as outras estão erradas:\n\nA) Obrigar o detetive a sempre usar a mesma lupa primeira vez, mesmo quando ele sabe que precisa do pozinho, faz ele perder tempo atoa.\nC) Ficar brigando com o detetive e mandando ele tentar de novo depois que ele já deu a resposta errada é chato e ineficiente.\nD) Só pedir \"por favor, não esqueça das ferramentas\" ainda dá a chance dele esquecer. Melhor travar a regra direto no sistema!\n\nDica importante:\nEm vez de só pedir para o robô fazer algo no texto, use os \"botões e regras fixas\" do sistema para obrigar ele a fazer certo de primeira.",
        "opt_trans": {
            "A": "Forçar get_customer como a ferramenta necessária para todos os turnos, e então deixar o Claude decidir se ferramentas adicionais são necessárias.",
            "B": "Configurar tool_choice como 'any' para que o Claude deva chamar uma ferramenta disponível enquanto mantém a seleção baseada no modelo entre ferramentas aplicáveis.",
            "C": "Tentar novamente (retry) sempre que o texto do assistente soar genérico, usando correspondência de frases para continuar o loop até que uma ferramenta apareça.",
            "D": "Manter tool_choice em 'auto' e fortalecer as instruções do prompt do sistema exigindo uma consulta ao backend antes de cada resposta ao cliente."
        }
    },
    "034": {
        "correct": "B",
        "trans_q": "Cenário: Claude Code para Integração Contínua\nVocê está integrando o Claude Code ao seu pipeline CI/CD. O sistema executa revisões automáticas, gera testes e dá feedback em PRs. Seu job de revisão emite descobertas estruturadas que sempre passam no parse de JSON e campos obrigatórios. No entanto, logs de produção mostram algumas descobertas referenciando números de linhas fora do diff, classificando problemas de teste como bloqueadores de produção, ou incluindo texto de remediação que contradiz o problema relatado. Qual mudança melhoraria a confiabilidade mais efetivamente antes de postar os comentários?",
        "tech_exp": "A pergunta trata de validação híbrida (LLM + código tradicional) para garantir a qualidade de artefatos estruturados.\n\nPor que a alternativa B é a correta:\nMesmo com saídas estruturadas perfeitas em termos de esquema JSON, os LLMs podem gerar valores semanticamente incorretos (como apontar para uma linha que não foi alterada no PR). A solução arquitetural ideal é manter o output estruturado e acionar uma camada de validação de software tradicional posterior (ex: checar contra o arquivo de diff verdadeiro). Se os valores semânticos estiverem incorretos (linha fora do diff, severidade incompatível), essa camada intercepta e evita a postagem do comentário, funcionando como um 'Semantic Guardrail'.\n\nPor que as outras estão erradas:\n\nA) Substituir por texto markdown natural elimina as garantias estruturadas que já funcionavam, e parsear linguagem natural em busca de contradições é muito mais frágil e propenso a erros.\nC) Apenas dar instruções extras no prompt e baixar a temperatura não garante deterministicamente que ele não errará as linhas ou a severidade, LLMs não são calculadoras perfeitas.\nD) Tornar os campos obrigatórios no JSON Schema já é o comportamento atual do problema (\"always pass JSON parsing and required-field checks\"), isso não evita valores obrigatórios preenchidos com informações semânticas falsas.\n\nDica importante:\nNunca confie apenas em instruções no prompt para regras de negócios críticas e precisão determinística (como matemática de números de linha). Sempre combine outputs estruturados do LLM com validação determinística no código Python/TS (Guardrails Pattern).",
        "child_exp": "A missão do revisor de redação 📝\nImagine um revisor que preenche um formulário perfeitamente sem pular nenhuma linha, mas às vezes ele diz \"A palavra na linha 200 está errada\", sendo que o texto só tem 50 linhas! Ele escreveu direitinho no campo, mas a informação é maluca.\n\nPor que a alternativa B é a correta:\nA solução é manter o formulário dele, mas colocar um computador normal para checar as respostas: \"Ei, essa linha existe mesmo? Esse erro é mesmo grave?\". Se a checagem falhar, o computador não deixa a revisão ser publicada para o autor não ficar confuso.\n\nPor que as outras estão erradas:\n\nA) Pedir para ele não usar o formulário e escrever um texto livre deixaria muito mais difícil checar se as linhas existem.\nC) Pedir \"por favor, olhe com muito cuidado as linhas\" não garante que ele não vai cometer o mesmo erro matemático de novo.\nD) Obrigar ele a preencher o campo não resolve, porque ele já preenchia! O problema é que ele preenchia com a linha errada.\n\nDica importante:\nRobôs que escrevem textos são ótimos com palavras, mas péssimos com números e contas. Sempre use a programação normal para checar se as linhas e matemáticas que eles inventaram estão certas!",
        "opt_trans": {
            "A": "Substituir o uso de ferramentas por saída em markdown e analisar a explicação em linguagem natural em busca de contradições antes de postar os comentários de revisão.",
            "B": "Manter a saída estruturada baseada em ferramentas, e então adicionar validação semântica contra metadados do diff, regras de severidade e consistência das descobertas antes de publicar comentários.",
            "C": "Diminuir a temperatura e instruir o Claude a verificar duas vezes cada caminho de arquivo, número de linha, severidade e remediação antes de retornar os resultados.",
            "D": "Tornar obrigatório cada campo de descoberta no esquema JSON para que o Claude não possa omitir valores incertos durante a geração automática de revisão."
        }
    },
    "035": {
        "correct": "A",
        "trans_q": "Cenário: Agente de Suporte ao Cliente\nVocê tem um agente de suporte com subagentes especializados (verificação, cobrança, retornos). Engenheiros querem que subagentes passem resultados parciais diretamente entre si para resolver disputas mais rápido. Em testes, essas descobertas trocadas diretamente às vezes ignoram notas de escalonamento e deixam a resposta final do cliente sem explicar por que um subagente tentou refazer uma busca que falhou. Qual mudança de arquitetura melhora melhor a confiabilidade sem eliminar a especialização?",
        "tech_exp": "A pergunta examina padrões de comunicação e estado em arquiteturas Multi-Agente (Orquestração vs Coreografia).\n\nPor que a alternativa A é a correta:\nEm arquiteturas multi-agente complexas, a passagem de mensagens peer-to-peer (coreografia) perde rapidamente a rastreabilidade do contexto e dificulta agregar o estado global final de forma coesa para o cliente. Ao centralizar as requisições através de um nó Coordenador (Supervisor Pattern), o coordenador age como a 'memória' central, registrando erros, retentativas e racional de cada subagente. Ele garante que a resposta final contenha todo o contexto necessário, mantendo a especialização dos agentes inalterada, apenas mudando o canal de comunicação para uma estrela (star topology).\n\nPor que as outras estão erradas:\n\nB) Passar mensagens diretamente com resumos não resolve a perda sistemática de estado e a falta de controle de quem, no final, consolida o estado mestre sem esquecer dos detalhes cruciais de um terceiro agente.\nC) Dar todas as ferramentas para todos os subagentes quebra completamente o propósito e os benefícios do isolamento e especialização (Separation of Concerns/Least Privilege).\nD) Fazer o último agente montar a resposta final é perigoso, pois ele só terá a visibilidade do que lhe foi passado em cadeia, frequentemente perdendo contexto vital do início da requisição e acoplando a lógica de resposta a uma ordem de execução arbitrária.\n\nDica importante:\nEm fluxos Multi-Agente críticos, prefira sempre o Padrão Supervisor (Supervisor/Coordinator Pattern). Um orquestrador central despachando tarefas para subagentes garante um estado global rastreável e unificado, prevenindo o caos do envio direto de mensagens peer-to-peer.",
        "child_exp": "A missão do trabalho em grupo 🧑‍🏫\nImagine um grupo de especialistas: um olha identidade, um olha o banco e outro olha o pacote. Se eles ficarem apenas cochichando entre si no ouvido, no final a apresentação fica toda bagunçada porque a última pessoa não ouviu direito o que o primeiro disse!\n\nPor que a alternativa A é a correta:\nA melhor forma é ter um \"Líder do Grupo\" (o Coordenador). Quando alguém descobre algo, entrega um papel pro Líder. O Líder lê tudo, guarda na pasta e decide quem faz o que depois. Assim, no final, o Líder consegue escrever uma resposta completinha com as informações de todo mundo sem perder nada!\n\nPor que as outras estão erradas:\n\nB) Pedir para eles escreverem resumos na hora de cochichar um com o outro ainda mantém a bagunça de passar informações sem controle central.\nC) Dar acesso ao banco e ao pacote para todos eles ao mesmo tempo acaba com os especialistas — vira uma bagunça onde todo mundo tenta fazer tudo!\nD) Deixar a última pessoa que trabalhou dar a resposta final é arriscado, pois ela pode não saber de um problema importante que o primeiro especialista resolveu logo no início.\n\nDica importante:\nSempre que muitas pessoas (ou robôs) trabalharem juntas, tenha alguém no meio para coordenar e anotar tudo. Isso evita que as informações se percam como em um telefone sem fio!",
        "opt_trans": {
            "A": "Roteie todas as solicitações e resultados de subagentes através do coordenador, que registra contexto, erros e as entradas para resolução final.",
            "B": "Permitir que subagentes enviem mensagens uns aos outros diretamente, mas exija que cada mensagem inclua um resumo em texto livre da lógica e justificativa.",
            "C": "Dar a cada subagente acesso a todas as ferramentas MCP, para que os agentes possam verificar de forma independente o contexto que falta antes de responder.",
            "D": "Fazer com que o último subagente invocado produza a resposta ao cliente, usando quaisquer descobertas que ele já tenha recebido."
        }
    },
    "036": {
        "correct": "A",
        "trans_q": "Cenário: Extração Estruturada de Dados\nSeu sistema extrai dados de documentos. Sua execução noturna submete 30.000 requisições de extração de documentos. O job que processa os resultados deve atualizar o registro correto downstream e re-submeter apenas falhas. Durante testes, notou-se que depender da ordem das linhas no arquivo de resultado cria desalinhamentos ocasionais após retentativas e tratamento de falhas parciais. Qual design deve ser usado?",
        "tech_exp": "A pergunta trata de processamento assíncrono em lote (Batch Processing) e conciliação de dados em fluxos com LLMs.\n\nPor que a alternativa A é a correta:\nEm sistemas distribuídos e fluxos de LLM em lote (como a Batch API), o retorno de tarefas que incluem retentativas, falhas e assincronia destrói garantias de ordenação sequencial. A solução madura é anexar um identificador de correlação estável e único (custom_id) na requisição, que a API devolve intocado. Isso permite conciliar de forma exata e idempotente cada resultado (sucesso ou falha) de volta com o banco de dados de origem, sem depender da posição em arrays.\n\nPor que as outras estão erradas:\n\nB) Assumir ordenação sequencial em arrays é exatamente o que está causando a quebra do sistema e desalinhamentos relatados na premissa.\nC) Pedir ao LLM para incluir o nome do arquivo (nome de origem) no output gerado é perigoso, pois o LLM pode alucinar, esquecer, alterar maiúsculas/minúsculas, falhar em gerar a chave JSON, ou o processamento falhar antes do LLM gerar algo.\nD) Tentar colocar 30.000 documentos em uma única requisição quebrará os limites de janela de contexto massivamente e, se falhar, perderá todo o lote, destruindo a escalabilidade.\n\nDica importante:\nEm integrações em Batch e sistemas distribuídos, sempre use o padrão de 'Correlation ID' (IDs customizados passados na requisição que são ecoados na resposta). Nunca dependa da ordem de arrays ou de chaves geradas textualmente pelo LLM para mapeamento de entidades críticas.",
        "child_exp": "A missão da lavanderia 🧺\nImagine que você manda 30.000 camisetas para lavar. Se você achar que a lavanderia vai devolver as camisetas exatamente na mesma ordem que você entregou, você vai acabar entregando a camiseta de uma pessoa para a outra!\n\nPor que a alternativa A é a correta:\nA melhor ideia é colocar uma etiqueta com um número único (custom_id) em cada camiseta ANTES de lavar. Quando a lavanderia devolver, você só olha a etiqueta e sabe perfeitamente de quem é, não importa se atrasou, se voltou no início ou no fim do monte.\n\nPor que as outras estão erradas:\n\nB) Confiar na ordem é o erro que causou toda a confusão para começo de história.\nC) Pedir para a máquina de lavar tentar escrever o nome do dono na camiseta pode dar errado se a máquina se confundir ou escrever o nome com erro de digitação.\nD) Tentar colocar 30.000 camisetas na máquina de lavar de uma vez só vai quebrar a máquina inteira e explodir de tão pesada!\n\nDica importante:\nQuando mandar robôs fazerem um monte de coisas ao mesmo tempo, sempre coloque etiquetas (IDs únicos) nas tarefas. Assim, quando eles devolverem pronto, você sabe exatamente de onde veio!",
        "opt_trans": {
            "A": "Atribuir um custom_id estável derivado de cada registro de documento, persisti-lo com metadados de solicitação e reconciliar os resultados usando esse identificador.",
            "B": "Assumir que os resultados do lote preservam a ordem de envio e, em seguida, juntar cada resposta ao manifesto original pela sua posição no array.",
            "C": "Pedir ao Claude para incluir o nome do arquivo fonte em cada extração e analisar esse campo ao processar falhas.",
            "D": "Enviar uma requisição combinada contendo todos os documentos, para que cada extração e falha apareçam em uma única saída ordenada."
        }
    },
    "037": {
        "correct": "B",
        "trans_q": "Cenário: Agente de Resolução de Suporte ao Cliente\nNo repositório do agente, uma regressão aparece apenas nos arquivos de fixture de teste cujos nomes terminam em 'policy-case.json'. Essas fixtures estão espalhadas por múltiplos pacotes, e você quer que o Claude Code identifique os arquivos afetados antes de inspecionar seus conteúdos. Qual abordagem é a mais apropriada?",
        "tech_exp": "A pergunta avalia o conhecimento das ferramentas internas (built-in) de sistemas agentic para navegação e filtragem eficiente de arquivos no sistema de arquivos local.\n\nPor que a alternativa B é a correta:\nUtilizar a ferramenta de `Glob` com um padrão curinga específico (`**/*policy-case.json`) é a maneira mais eficiente, canônica e de menor custo computacional para encontrar caminhos de arquivos espalhados em uma base de código. Essa ferramenta foi projetada justamente para pré-filtrar listas de arquivos. Uma vez identificados os caminhos relevantes e validados pelo agente, ele pode utilizar a ferramenta `Read` focada de forma eficiente apenas nos arquivos que importam.\n\nPor que as outras estão erradas:\n\nA) Ler recursivamente todos os diretórios (e possivelmente os arquivos neles) consome token limits (janela de contexto) de forma massiva e extremamente lenta, pedindo para o LLM fazer um trabalho mecânico que o sistema operacional faz instantaneamente.\nC) Rodar comandos bash (como `find`) e jogar a lista completa sem filtragem otimizada é sub-ótimo e expõe o sistema a falhas, quando ferramentas nativas como Glob existem primariamente para segurança e consistência multi-plataforma dentro do sandbox do agente.\nD) Usar `Grep` busca por *conteúdos* textuais dentro dos arquivos, e não pelo *nome* dos arquivos. A regressão está identificada por um sufixo no nome do arquivo, portanto o grep no conteúdo procuraria algo diferente.\n\nDica importante:\nEm ferramentas de agente como o Claude Code ou Cline, entenda quando usar cada ferramenta nativa: Use `Glob`/`List` para descobrir estruturas de pastas e buscar por nomes de arquivos, e use `Grep`/`Search` quando precisar achar padrões de código dentro do conteúdo dos arquivos.",
        "child_exp": "A missão de achar os brinquedos 🧸\nImagine que você tem dezenas de quartos na sua casa, e perdeu os brinquedos que terminam com o nome \"policy-case.json\". Você precisa encontrá-los antes de abri-los para consertar.\n\nPor que a alternativa B é a correta:\nUsar o \"Glob\" é como ter um raio-X mágico que você aponta para a casa inteira e diz: \"Só ilumine as caixas que terminem com 'policy-case.json'\". É super rápido e eficiente, e você vai exatamente onde precisa ir!\n\nPor que as outras estão erradas:\n\nA) Sair abrindo quarto por quarto, gaveta por gaveta, e olhando tudo seria extremamente cansativo e demorado.\nC) Fazer malabarismos complicados com ferramentas antigas não é seguro quando você já tem uma ferramenta nova que faz exatamente isso de forma limpa.\nD) Usar o \"Grep\" seria como procurar brinquedos abrindo cada um deles e lendo o que está escrito no plástico lá dentro, em vez de só ler o nome da etiqueta por fora.\n\nDica importante:\nSempre use a ferramenta certa para o trabalho certo! Para achar arquivos pelo nome, use o Glob. Para achar palavras lá dentro do arquivo, use o Grep.",
        "opt_trans": {
            "A": "Ler todos os diretórios de pacotes recursivamente, e então pedir ao Claude para inferir quais nomes de arquivo correspondem à convenção de nomenclatura de fixture.",
            "B": "Usar o Glob com '**/*policy-case.json', revisar os caminhos correspondidos, e então Ler (Read) apenas os arquivos de fixture relevantes.",
            "C": "Usar Bash para executar comandos recursivos de listagem de arquivos, e então colar a saída completa na conversa para filtragem.",
            "D": "Usar Grep por 'policy-case' através do conteúdo do repositório, e então Ler (Read) todo arquivo retornado pela pesquisa de conteúdo."
        }
    },
    "038": {
        "correct": "A",
        "trans_q": "Cenário: Agente de Suporte ao Cliente\nDurante uma investigação de várias horas, o agente identifica corretamente arquivos e casos extremos importantes. Mais tarde na mesma sessão, ele começa a contradizer descobertas anteriores, menciona padrões genéricos de sistema de suporte e pede para redescobrir classes que ele já inspecionou. Qual mudança melhoraria a confiabilidade para o resto da investigação?",
        "tech_exp": "A pergunta trata de problemas de degradação da janela de contexto (context window drift) e retenção de estado (Memory) em longas sessões de interação de agentes.\n\nPor que a alternativa A é a correta:\nA degradação no desempenho e o comportamento cíclico (esquecer o que já viu) ocorrem quando o LLM é expulso do seu contexto principal devido ao tamanho de respostas longas e ruído no histórico. A prática recomendada na arquitetura de agentes é o 'External Memory' ou 'Scratchpad Pattern': instruir o agente a criar, manter e ler ativamente um documento markdown no sistema de arquivos local (o scratchpad) com o estado global consolidado, conclusões e mapeamento de arquivos. Isso ancora o agente em estado persistente, não importando a duração da sessão.\n\nPor que as outras estão erradas:\n\nB) Reiniciar a sessão a cada falha ou ciclo inconsistente joga fora todo o trabalho valioso que já foi alcançado, gastando incontáveis tokens/dinheiro e tempo para refazer passos conhecidos.\nC) A maioria dos sistemas não suporta um comando /compact e, mais importante, compactação automática perde nuances; a criação ativa de notas pelo próprio agente garante que as regras de negócios críticas sejam registradas.\nD) Anexar constantemente todo o output bruto e completo de ferramentas a cada novo passo consumirá exponencialmente a janela de contexto muito rapidamente, acelerando os problemas de contradição e alucinação e atingindo o limite máximo de tokens quase imediatamente.\n\nDica importante:\nEm fluxos agentic estendidos (long-running tasks), use sempre um 'Memory File' (como TODO.md ou SCRATCHPAD.md). O agente usa suas ferramentas de Escrita e Leitura nesse arquivo para simular uma memória de longo prazo confiável que sobrevive a contextos longos.",
        "child_exp": "A missão do aventureiro na floresta 🗺️\nImagine um explorador que está andando em uma floresta gigante há horas. De repente, ele esquece que já passou pela árvore grande e quer voltar para ver o que tem atrás da mesma pedra.\n\nPor que a alternativa A é a correta:\nSe o explorador sempre andar com um bloquinho de notas no bolso (scratchpad) e for anotando \"A árvore grande está na direita\" e \"A pedra não tem nada\", ele nunca vai se perder nem esquecer o que já fez. Quando tiver dúvida, ele só precisa ler o próprio bloquinho!\n\nPor que as outras estão erradas:\n\nB) Apagar a memória dele e mandar ele voltar correndo pro início da floresta toda vez que ele esquecer algo seria terrível e ele nunca chegaria no final.\nC) Ficar pedindo pra ele fechar os olhos e meditar toda hora pra resumir as coisas pode fazer ele esquecer detalhes das árvores e dos monstros importantes.\nD) Se ele carregar pedaços de todas as pedras, árvores e placas que ele achou em uma mochila gigante nas costas o tempo inteiro, ele vai ficar tão pesado que não vai conseguir dar mais nenhum passo!\n\nDica importante:\nQuando tiver uma tarefa muito longa, seja você ou um robô, anote as descobertas em um bloquinho! Isso economiza cabeça e garante que as coisas importantes não vão fugir da memória.",
        "opt_trans": {
            "A": "Fazer com que os agentes mantenham arquivos scratchpad concisos com descobertas-chave, caminhos de arquivo e decisões, e então referenciá-los em prompts posteriores.",
            "B": "Reiniciar a sessão sempre que as respostas se tornarem inconsistentes e exigir que o agente escaneie todo o repositório novamente.",
            "C": "Usar /compact após cada chamada principal de ferramenta para que a conversa inteira permaneça resumida antes que investigações adicionais continuem.",
            "D": "Anexar todo resultado bruto de ferramenta a cada solicitação subsequente para que o agente possa reconsiderar toda a evidência descoberta a cada turno."
        }
    },
    "039": {
        "correct": "D",
        "trans_q": "Cenário: Agente de Suporte ao Cliente\nApós adicionar backends regionais, logs mostram que o agente às vezes interpreta mal os payloads brutos de lookup_order: uma região retorna status_code: 3, outra retorna state: \"RETURN_PENDING\", e uma terceira inclui timestamps aninhados. As respostas finais são inconsistentes. Qual mudança melhora a confiabilidade sem modificar cada implementação de ferramenta MCP?",
        "tech_exp": "A pergunta trata de normalização de dados e padrão adaptador (Adapter Pattern) no fluxo de entrada do LLM para mitigar alucinações causadas por heterogeneidade semântica.\n\nPor que a alternativa D é a correta:\nLLMs sofrem quando precisam resolver lógicas de negócios complexas implícitas (como mapear dezenas de formatos de dados para um significado unificado) puramente no raciocínio. Ao introduzir um hook (ou wrapper/middleware na camada cliente) que normaliza a saída disparatada das várias ferramentas de backend em um formato único e canônico de suporte, você desonera o modelo de linguagem de inferir estados. O modelo processará uma estrutura unificada e estritamente tipada, prevenindo interpretações incorretas de forma determinística, garantindo a arquitetura limpa.\n\nPor que as outras estão erradas:\n\nA) Pedir para o cliente inserir a região não resolve o problema: o agente ainda receberá formatos diferentes e confusos que ele precisará descompactar usando raciocínio não-determinístico (LLM).\nB) Expandir o System Prompt com lógicas de if/else e mapeamentos de códigos e chaves cria um prompt extremamente complexo e frágil. O contexto fica poluído, lento e propenso a falhas assim que a próxima região for adicionada.\nC) Fazer parse e criar retentativas baseadas em texto final de resposta é muito frágil, tentando consertar os sintomas em vez da doença central.\n\nDica importante:\nNunca delegue para o modelo de linguagem uma transformação determinística, estrutural e lógica que o código tradicional resolve em milissegundos. Padrão fundamental: Use código para normalizar/formatar, use o modelo apenas para raciocinar sobre o texto normalizado.",
        "child_exp": "A missão do tradutor de restaurantes 🍽️\nImagine um garçom que tem que pegar a comida em três cozinhas diferentes. A cozinha A entrega um papel dizendo \"3\", a cozinha B escreve \"PRONTO_PRA_SAIR\", e a cozinha C entrega um mapa de estrelas. O coitado do garçom tem que adivinhar se a comida está pronta ou não e acaba errando na hora de falar para o cliente.\n\nPor que a alternativa D é a correta:\nA melhor ideia é colocar um tradutor na porta das cozinhas! Antes do papel chegar no garçom, o tradutor pega o \"3\", o mapa de estrelas e o resto e converte tudo em um bilhete verde gigante dizendo: \"COMIDA PRONTA\". Assim o garçom (o robô) não precisa ficar quebrando a cabeça para entender, ele só lê e passa pra frente.\n\nPor que as outras estão erradas:\n\nA) Obrigar o cliente que está na mesa a dizer em qual cozinha a comida dele foi feita não ajuda muito, porque o garçom ainda vai ter que ler o bilhete confuso.\nB) Dar para o garçom um livro de regras de 500 páginas e dizer \"leia isso toda vez pra adivinhar as cozinhas\" vai deixar ele muito lento e chateado.\nC) Ficar brigando com o garçom depois que ele dá a resposta errada e mandar ele olhar o bilhete confuso de novo não ajuda nada.\n\nDica importante:\nSempre que puder, arrume a bagunça nos fios e caixas de dados ANTES de entregar para o robô inteligente ler. Ele é bom em conversar, mas detesta adivinhar quebra-cabeças misturados!",
        "opt_trans": {
            "A": "Exigir que a mensagem de cada cliente inclua a região dele para que o Claude possa escolher a interpretação correta do payload.",
            "B": "Expandir o prompt do sistema com cada mapeamento de status regional e pedir ao Claude para normalizar os payloads durante a geração da resposta.",
            "C": "Fazer parse do texto final do assistente em busca de palavras de status e tentar lookup_order novamente sempre que a redação parecer inconsistente.",
            "D": "Adicionar um hook PostToolUse que transforma saídas do lookup_order em uma estrutura de caso de suporte canônica antes que o Claude as receba."
        }
    },
    "040": {
        "correct": "A",
        "trans_q": "Cenário: Geração de Código com Claude Code\nO trabalho noturno de CI pede ao Claude para propor testes. Sugestões são consistentemente de baixo valor: duplicação de snapshots, mocks desnecessários e ignorando regras do time. Desenvolvedores rodam o trabalho em runners efêmeros, então preferências locais não existem. Qual mudança melhoraria mais a qualidade das sugestões de teste geradas?",
        "tech_exp": "A pergunta trata de como prover orientações de sistema contextuais persistentes no ciclo de vida de desenvolvimento e pipelines de integração.\n\nPor que a alternativa A é a correta:\nO Claude Code permite a criação de arquivos `CLAUDE.md` no nível do repositório para estipular instruções personalizadas e persistentes. Quando um CI Runner efêmero baixa o repositório, ele baixa esse arquivo automaticamente junto com o código e inicializa o contexto global com as diretrizes da equipe (ex: \"use testes de comportamento em vez de snapshots\", \"aqui estão as convenções de mock do time\"). Isso estabelece consistência institucional independentemente de quem, ou de qual máquina física executa a tarefa.\n\nPor que as outras estão erradas:\n\nB) Adicionar um aviso vago no prompt para \"ser conservador\" não guia o modelo tecnicamente sobre *quais* são as regras, apenas inibe a geração, produzindo ainda menos valor.\nC) Armazenar `~/claude/CLAUDE.md` no laptop de um desenvolvedor cria um estado local na máquina, inacessível aos Runners de CI efêmeros que trabalham no backend de integração contínua.\nD) Ocultar testes reais do contexto do modelo o força a \"adivinhar à cegas\" o padrão arquitetural do projeto de testes e os frameworks em uso, e resulta no LLM alucinando mocks incorretos ou padrões completamente divergentes da cultura técnica do repositório.\n\nDica importante:\nA ferramenta principal do Claude Code para alinhamento e cultura de código não é o prompt da interface, mas sim o arquivo `CLAUDE.md` commitado junto com o código. É o padrão de 'Codebase Guidelines as Code'.",
        "child_exp": "A missão das regras do time ⚽\nImagine um novo jogador de futebol robô que entra para o time, mas ele não sabe que o time só joga tocando a bola curto, e fica dando chutão para o alto! Todo jogo ele faz a mesma coisa errada e os jogadores reclamam.\n\nPor que a alternativa A é a correta:\nA solução é simples: escreva um grande cartaz com as regras (o arquivo CLAUDE.md) e cole no vestiário do próprio time (no repositório do projeto). Toda vez que qualquer robô entrar no time, a primeira coisa que ele faz é ler o cartaz e dizer \"Ah, entendi! Aqui no time a gente toca curto e não dá chutão\".\n\nPor que as outras estão erradas:\n\nB) Só gritar \"toma cuidado\" não ajuda ele a entender as regras do passe de bola, só deixa o robô com medo de jogar.\nC) Se o capitão do time guardar as regras trancadas na gaveta da casa dele, nenhum robô vai poder ler as regras no dia do jogo.\nD) Esconder os vídeos das jogadas antigas só piora as coisas! O robô vai ter que adivinhar como se joga, e com certeza vai dar o chutão errado.\n\nDica importante:\nRegras de projeto não devem estar espalhadas em manuais de fora; escreva elas num arquivo (CLAUDE.md) grudado no seu código e todos vão trabalhar no mesmo estilo!",
        "opt_trans": {
            "A": "Fazer commit de orientações CLAUDE.md em nível de projeto descrevendo critérios de teste valiosos, convenções de fixture e ajudantes reutilizáveis para o Claude Code invocado por CI.",
            "B": "Adicionar uma linha de prompt pedindo ao Claude para ser conservador e evitar testes desnecessários sempre que revisar arquivos alterados na CI.",
            "C": "Armazenar o estilo de teste preferido em ~/claude/CLAUDE.md no laptop do mantenedor e copiar as saídas para os pull requests.",
            "D": "Exigir que os desenvolvedores omitam os arquivos de teste existentes do contexto de CI para que o Claude deduza as necessidades de cobertura apenas a partir do código do produto."
        }
    },
    "041": {
        "correct": "B",
        "trans_q": "Cenário: Agente de Suporte ao Cliente\nLogs de produção mostram que solicitações simples como \"reenviar link de rastreamento\" demoram tanto quanto casos multi-problemas, porque passam por TODOS os subagentes especialistas, inserindo ruído nas respostas finais. Casos complexos ainda requerem múltiplos especialistas. Qual mudança melhora a orquestração?",
        "tech_exp": "A pergunta avalia o padrão de roteamento dinâmico (Dynamic Routing) na Orquestração Multi-Agente.\n\nPor que a alternativa B é a correta:\nFazer um fluxo fixo (pipelines lineares) onde cada solicitação obrigatoriamente passa por agentes irrelevantes gasta recursos e introduz degradação de contexto. O coordenador deve ser capaz de realizar um \"Triage\" e delegar (rotear) a sub-tarefa APENAS para subagentes cuja especialização seja essencial para a intenção detectada (ex: só o de logística para links de rastreio). O coordenador então pega esse retorno direto e forma a resposta. Isso escala para intenções múltiplas e simples com eficiência e isolamento do ruído.\n\nPor que as outras estão erradas:\n\nA) Diminuir os `max_tokens` não impede a perda de velocidade e o risco de contexto barulhento; apenas corre o risco adicional de o subagente cortar mensagens ao meio com respostas incompletas.\nC) Fazer subagentes trocarem mensagens entre si não resolve o problema principal, que é agentes não-necessários estarem processando requisições que não lhes pertencem — criando uma complexidade peer-to-peer desnecessária.\nD) Roteamento único (single specialist) para todas as solicitações, ignorando problemas compostos a não ser explicitados textualmente, falhará massivamente nos \"casos complexos que ainda requerem múltiplos especialistas\" exigidos no cenário.\n\nDica importante:\nEm orquestração, use um 'Router/Triage Agent' como o nó central. Ele lê a intenção inicial e decide o plano de roteamento para invocar as menores partes e os subagentes estritamente necessários (Dynamic Dispatch).",
        "child_exp": "A missão da consulta no hospital 🏥\nImagine que você vai ao hospital porque quer só um band-aid no dedinho. Mas em vez da enfermeira te dar logo o curativo, ela te manda primeiro fazer exame de sangue, raio-X da barriga e falar com o dentista. Só depois você pega o band-aid e vai embora!\n\nPor que a alternativa B é a correta:\nÉ muito melhor colocar uma pessoa esperta na recepção (o Coordenador). Você diz: \"Quero só o rastreamento\". A recepção diz: \"Ok, vá só na sala da logística e vá pra casa feliz\". Se a pessoa disser \"Preciso de devolução E também mudar o cartão\", a recepção aponta duas portas. Rápido, sem exames doloridos e sem atrasos.\n\nPor que as outras estão erradas:\n\nA) Pedir para todos os médicos fazerem os exames bem rapidinho, falando pouco, não resolve. Você ainda passa por 5 médicos atoa e atrapalha todos.\nC) Deixar os médicos gritarem um com o outro nos corredores para se organizarem sozinhos sem a recepção acaba bagunçando mais.\nD) Se só existe uma porta permitida por vez, se você aparecer precisando do coração E de um curativo, vão te atender mal porque o sistema quebrou.\n\nDica importante:\nNão perca tempo chamando robôs inteligentes para trabalhar em coisas que não precisam deles! Uma boa recepção faz tudo fluir.",
        "opt_trans": {
            "A": "Manter a sequência fixa de especialistas, mas diminuir os max_tokens de cada subagente para que requisições simples terminem com menos sobrecarga.",
            "B": "Fazer com que o coordenador avalie o escopo da requisição, delegue apenas para subagentes especialistas relevantes e agregue suas descobertas em uma resposta.",
            "C": "Permitir que os subagentes especialistas enviem mensagens uns aos outros diretamente, permitindo que o agente que terminar primeiro monte a resposta final ao cliente.",
            "D": "Rotear cada solicitação para um único especialista correspondido por palavras-chave, contornando a agregação, a menos que o cliente pergunte explicitamente sobre vários problemas."
        }
    },
    "042": {
        "correct": "B",
        "trans_q": "Cenário: Claude Code para Integração Contínua\nUm engenheiro sênior criou um fluxo /pr-feedback que funciona no laptop dele, mas novos contribuidores e servidores CI limpos acusam erro de \"comando não encontrado\". Você quer que o mesmo comando esteja disponível e revisado junto com as mudanças do código. O que fazer?",
        "tech_exp": "A pergunta trata de provisionamento e consistência de ambiente para integrações GitOps / CI com ferramentas agentic.\n\nPor que a alternativa B é a correta:\nO recurso de custom slash commands (`/commands`) do Claude Code, assim como configurações globais do LLM, deve seguir os princípios de \"Infraestrutura como Código\" (IaC) se pretendem ser universais e integrados ao CI/CD. Em vez de arquivos vivendo no diretório home (usuário local), criar uma pasta `.claude/commands` no repositório do projeto, contendo os prompts persistidos em versionamento Git, garante que qualquer runner remoto, container ou novo colaborador tenham exatamente o mesmo alinhamento comportamental out-of-the-box.\n\nPor que as outras estão erradas:\n\nA) Embutir textos gigantes de checklist hard-coded nos steps do pipeline YAML do CI é verboso, difuso, extremamente complexo de dar manutenção e impede os desenvolvedores de usarem o comando facilmente no dia a dia nas suas próprias máquinas.\nC) Embora o `CLAUDE.md` seja para cultura global, colocar instruções massivas de um script específico (como o step-by-step de PR review) dilui a atenção do modelo sobre regras core. Além disso, forçaria a equipe a digitar o longo prompt e lembrar-se de todo o fluxo manualmente no lugar de usar o atalho prático `/pr-feedback`.\nD) Manter comandos na pasta `~/claude/` (Home directory do sistema operacional) quebra o fluxo de DevOps, exigindo setups manuais e manuais wiki frágeis que sempre acabam quebrando e dessincronizados na CI.\n\nDica importante:\nConfigurações de agentes de integração (prompts, tool manifests, comandos customizados) devem viver com o projeto versionado, lado-a-lado com as regras de pipeline (Project-level configuration > System-level configuration).",
        "child_exp": "A missão da receita de bolo escondida 🍰\nImagine um padeiro que inventou uma receita de bolo perfeita, mas ele guardou o papel debaixo do travesseiro em sua própria casa. No dia que os ajudantes vão para a cozinha e tentam assar, o forno diz \"Receita não encontrada\" porque o papel não está lá!\n\nPor que a alternativa B é a correta:\nA melhor ideia é o padeiro levar o caderninho para o balcão da cozinha (no repositório do código) e pendurá-lo lá! Agora qualquer máquina ou qualquer novo funcionário que entra só precisa olhar pro caderninho que veio junto com a farinha, e tudo vai dar certo.\n\nPor que as outras estão erradas:\n\nA) Se escrevermos a receita em todos os sacos de lixo e embalagens do forno ao mesmo tempo, quando mudarmos o bolo teremos que raspar os sacos antigos todos um por um.\nC) Misturar a receita daquele bolo gigantesco dentro das regras gerais da loja (\"Não correr\") vai fazer as regras ficarem gigantes. Além disso, as pessoas terão que digitar tudo de cabeça.\nD) Continuar com a receita na casa do padeiro e só pedir para cada ajudante dirigir até lá pra copiar o papel não faz o menor sentido e gasta tempo demais!\n\nDica importante:\nSe um comando precisa ser acessado por vários computadores e todo mundo precisa rodar junto com o projeto, coloque o arquivo do comando DENTRO do projeto! Simples assim.",
        "opt_trans": {
            "A": "Embutir o checklist de revisão diretamente em cada etapa do fluxo de trabalho para que cada job de pipeline construa seu próprio prompt.",
            "B": "Armazenar o markdown do comando em claude/commands/ no repositório e confirmá-lo (fazer commit) com as mudanças de fluxo de trabalho do CI.",
            "C": "Mover o checklist para o CLAUDE.md e instruir os revisores a digitar o mesmo prompt sempre que a CI precisar de revisão.",
            "D": "Manter o comando em ~/claude/commands/ e adicionar instruções de integração para que cada desenvolvedor e executor o copie."
        }
    },
    "043": {
        "correct": "D",
        "trans_q": "Cenário: Extração Estruturada de Dados\nAuditorias mostram que uma categoria de feedback rotulada como \"termos de pagamento ambíguos\" está sendo descartada em 68% dos casos. Como resultado, os revisores começaram a ignorar todo o feed de QA, perdendo achados vitais. O que você deve fazer a seguir?",
        "tech_exp": "A pergunta trata de tolerância a erro e combate ao Efeito de Fadiga de Alerta (Alert Fatigue) em relatórios gerados por LLMs.\n\nPor que a alternativa D é a correta:\nSistemas automatizados caem no descrédito e perdem sua utilidade completamente se emitirem falsos positivos frequentes. Os humanos simplesmente deixarão de checar (\"Cry Wolf effect\"). A melhor e única intervenção prática para salvar a eficácia do sistema é remover (suprimir) temporariamente a regra e a classificação ofensoras que produzem 68% de descartes, refinar os exemplos/instruções para precisão do agente nos bastidores, e proteger imediatamente os 32% (ou mais) das outras regras vitais que são exatas de serem ignoradas.\n\nPor que as outras estão erradas:\n\nA) Adicionar instruções genéricas como \"tenha certeza\" ou \"seja conservador\" é ineficaz para LLMs, pois não redefine especificamente a fronteira decisória confusa entre um termo bom e um 'ambíguo'. É um comando vago sem aterramento em regras.\nB) Manter a categoria ativada apenas treinará os usuários a fecharem abas sem olhar. Em poucas semanas, o valor global do projeto inteiro será zero.\nC) Aumentar o threshold global (nível de confiança) de todo o sistema apagará indiscriminadamente todas as checagens precisas e seguras só por causa de um caso de borda problemático, o que é danoso e ilógico.\n\nDica importante:\nA tolerância a falsos positivos em painéis para intervenção humana deve ser extremamente baixa. Regras isoladas ofensoras não devem punir a taxa de alerta do sistema global; desligue rapidamente ferramentas ou agentes imprecisos, limpe-os, depois religue-os.",
        "child_exp": "A missão do guarda cachorro 🐕\nImagine um cão de guarda que ladra o dia inteiro avisando: \"CARRO ROUBADO, CARRO ROUBADO!\" Mas em 68% das vezes é só o caminhão do vizinho passando. Chega um dia que o dono do cachorro desiste, e quando realmente um ladrão pula o muro, o dono nem acorda pra ver.\n\nPor que a alternativa D é a correta:\nA coisa mais importante a fazer é falar para o cão parar de ladrar pros carros da rua IMEDIATAMENTE (desligar só essa regra), enquanto a gente treina ele pra entender o que é vizinho e o que é bandido. Assim, se um ladrão aparecer, o dono vai escutar e confiar no aviso.\n\nPor que as outras estão erradas:\n\nA) Dizer pro cão \"tente ter certeza antes de latir\" não ajuda muito se você não explicar o que exatamente faz um carro ser um ladrão ou um vizinho.\nB) Deixar o cachorro latindo loucamente todo dia achando que é treinamento só vai enlouquecer o dono.\nC) Tentar tapar as orelhas do cachorro e pedir pra ele latir só quando for o fim do mundo também vai fazer ele perder avisos super importantes para outras regras vitais da casa.\n\nDica importante:\nSe um alarme pisca amarelo errado toda hora, as pessoas param de olhar, inclusive quando ele pisca vermelho! Desligue o barulho que incomoda antes que as pessoas quebrem a máquina de vez.",
        "opt_trans": {
            "A": "Adicionar uma instrução geral dizendo ao Claude para ser conservador e relatar apenas descobertas sobre as quais ele tenha alta confiança.",
            "B": "Manter todas as categorias de descobertas ativas e pedir aos revisores para descartarem itens incorretos até que dados suficientes se acumulem.",
            "C": "Aumentar o limite de confiança global para todas as descobertas de QA até que o volume geral caia para um nível aceitável.",
            "D": "Suprimir temporariamente a categoria de termos de pagamento ambíguos enquanto refina seus critérios e exemplos antes de reativá-la."
        }
    },
    "044": {
        "correct": "C",
        "trans_q": "Cenário: Agente de Suporte ao Cliente\nO coordenador envia subagentes com prompts longos que prescrevem sequências de ferramentas exatas e ramos condicionais. Esses subagentes falham em casos inusitados. Qual mudança melhora mais o desempenho preservando o controle do coordenador?",
        "tech_exp": "A pergunta testa a filosofia fundamental de engenharia de prompt para agentes autônomos: Micro-gerenciamento procedural vs Objetivos orientados (Goal-oriented prompting).\n\nPor que a alternativa C é a correta:\nAo tentar desenhar cadeias gigantescas de 'se isto faça aquilo' procedurais dentro do prompt do agente, você quebra a principal força do LLM: capacidade de inferir dinamicamente saídas baseadas no contexto de forma flexível. Agentes modernos e maduros requerem \"Guardrails Estruturais e Objetivos Declarativos\" em vez de pseudo-código. Reescrever os prompts focando em qual é o objetivo (estado final desejado), contexto, limites de segurança e formato JSON estrito deixa o agente usar seu raciocínio flexível para sobreviver e consertar sozinho os desvios inusitados.\n\nPor que as outras estão erradas:\n\nA) Expandir o prompt para tentar cobrir a unha e o parafuso de todo caso estranho e ramificação condicional possível só criará um prompt frágil, gigante e infinito, um anti-pattern extremo em orquestração.\nB) Exigir uma ordem de ferramenta fixa não tem o menor sentido, removendo justamente a flexibilidade que a IA oferece. Isso tornaria os subagentes equivalentes a um script Python ruim e rígido sem capacidade de reparo.\nD) Fazer o coordenador realizar 'parsing de texto livre' no resultado procurando palavras mágicas é criar integrações muito frágeis com o modelo na borda do ecossistema, propenso a desvios semânticos e regressões.\n\nDica importante:\nNunca micro-gerencie a execução de um LLM com lógicas procedurais gigantes e loops if/else textuais no prompt. Declare o objetivo, as métricas e obrigue uma saída rígida; e deixe as caixas-pretas de inteligência artificial calcularem sozinhas o caminho lógico ótimo no meio.",
        "child_exp": "A missão de seguir o mapa rígido 🗺️\nImagine um explorador brilhante ao qual você dá um mapa gigantesco com passos duros: \"Ande 5 passos e vire à esquerda\". Se tiver uma árvore caída exatamente no passo 5, ele trava e entra em pânico! E agora?\n\nPor que a alternativa C é a correta:\nA melhor maneira de liderar o explorador esperto é dizer: \"Aqui está sua missão final, vá até aquela montanha e pegue água! Você não pode atravessar a lava e me traga as coisas nesta caixa aqui\". Deixe a inteligência dele descobrir como desviar da árvore, pular e arranjar um jeito inteligente. Isso é muito melhor e ele nunca vai travar!\n\nPor que as outras estão erradas:\n\nA) Se você colocar as instruções ainda mais complicadas na folha dele com \"se tiver árvore caida dê a volta usando passo da macarena\", a folha vai ter milhares de páginas irreais!\nB) Mandar o explorador seguir uma linha no chão e se não estiver certo, parar tudo e chorar de volta pro chefe, não ajuda em absolutamente nada a autonomia.\nD) Obrigar o chefe a ficar olhando no binóculos para ver se o explorador levantou os braços fazendo um sinal e só assim continuar o trabalho atrapalha e cria atritos bobos.\n\nDica importante:\nNão lute ensinando o robô passo-a-passo no mínimo detalhe como se ele não tivesse um cérebro. Dê o Objetivo, as Fronteiras de perigo, e espere o resultado estruturado!",
        "opt_trans": {
            "A": "Expandir prompts delegados com ramos passo-a-passo mais detalhados cobrindo números de pedido em falta, problemas mistos e tipos de evidências inusitadas.",
            "B": "Exigir que os subagentes sigam uma ordem fixa de ferramentas e escalem sempre que qualquer campo intermediário esperado estiver indisponível.",
            "C": "Reescrever prompts delegados para declarar o objetivo de suporte, contexto conhecido, critérios de qualidade, restrições e formato de retorno estruturado obrigatório.",
            "D": "Fazer com que o coordenador analise a resposta de linguagem natural de cada subagente em busca de frases de conclusão antes de decidir se deve continuar."
        }
    },
    "045": {
        "correct": "D",
        "trans_q": "Cenário: Geração de Código com Claude Code\nUm dashboard relata 96% de aprovação para os artefatos gerados pelo Claude. Saídas aceitas concentram-se em READMEs, e rejeitadas em Schemas e banco de dados. A diretoria quer parar a revisão manual em todos onde o modelo se diz acima de 0.9 de confiança. Qual é o próximo passo mais confiável?",
        "tech_exp": "A pergunta explora as métricas de segurança, limiares de confiança não calibrados de modelos gerativos e governança de artefatos heterogêneos na adoção corporativa.\n\nPor que a alternativa D é a correta:\nA confiança probabilística interna dos LLMs reportada via meta-tokens não é perfeitamente calibrada (Model Overconfidence Problem). Um modelo muitas vezes reporta 99% de confiança errando matemática e lógica crítica em schemas bancários ou SQLs de alto impacto. Portanto, a redução da verificação humana nunca deve basear-se em um limiar numérico cego global (blanket confidence), mas sim separando a categorização do domínio que requer precisão vs criatividade. Liberar revisão para domínios de texto livre sem impacto arquitetônico severo e manter revisões pesadas em dados estruturados (APIs) balanceia velocidade com risco vital corporativo.\n\nPor que as outras estão erradas:\n\nA) Como LLMs mentem e alucinam com 99% de confiança com frequência (overconfidence bias em estruturas matemáticas/lógicas não-triviais), relaxar apenas por confiança deixará os buracos nos Schemas passarem com destruição real em produção.\nB) Aumentar amostragem estatística global ignora o desequilíbrio e assimetria das quebras (schemas quebrando pesam e custam milhões de vezes mais do que um typo num arquivo .md), e atrasará uma ação prática inteligente de segregar responsabilidades estruturadas.\nC) Assumir que incidentes e defeitos em produção servirão apenas como um alerta e não se importar com isso com antecedência é negligência extrema com o ambiente operacional, a confiança do time e as perdas de dados nas migrações com schemas furados.\n\nDica importante:\nNunca aceite os limiares de 'Confidence Score' reportados por LLMs em saídas não textuais cegamente, há um profundo viés de calibração neles. Estratégias seguras de 'Human-out-of-the-loop' são categorizadas com base no escopo e no impacto do erro do domínio, jamais de forma global.",
        "child_exp": "A missão da escola mágica 🧙\nImagine que o aluno inteligente diz para a professora: \"Pode confiar, eu tenho nota 9.9 em todas as tarefas, nunca mais corrija minhas provas!\" Mas a professora lembra: as redações de aventura e poemas ele é um artista espetacular, mas na aula da química de fazer poções, às vezes as poções explodem a escola inteira quando ele acha que sabe tudo.\n\nPor que a alternativa D é a correta:\nA resposta não é simplesmente confiar nele em tudo, nem não confiar. A escola faz uma regra inteligente: \"Ok, nas aulas de redação você não precisa mais ser corrigido (livre), mas nas aulas de química explosiva (bancos de dados e regras pesadas) você continuará precisando de assinatura da professora!\" Dividindo e focando o esforço.\n\nPor que as outras estão erradas:\n\nA) Como às vezes o aluno inteligente fala besteiras explosivas super empolgado achando que tá certíssimo, isso faria ele destruir a escola!\nB) Deixar o aluno continuar testando tudo aleatoriamente por meses a mais só esconde o problema das provas de poção que ele está perdendo consistentemente, criando atraso e insegurança no ambiente da escola mágica.\nC) Liberar tudo sem olhar, rezando que os pais no final do ano não percebam se alguma coisa explodir depois na vida adulta não soa razoável de jeito nenhum.\n\nDica importante:\nSepare as tarefas! Quando os sistemas computacionais são usados, diminua os filtros para trabalhos artísticos de palavras e aumente drasticamente a segurança (com humanos revisando) na parte dos números rigorosos.",
        "opt_trans": {
            "A": "Exigir que os revisores verifiquem apenas as saídas de baixa confiança, uma vez que resultados de alta confiança já passaram na avaliação agregada.",
            "B": "Aumentar o tamanho da amostra aleatória geral por mais duas sprints, e então decidir usando a taxa de aceitação combinada.",
            "C": "Adotar o limite de confiança de 0,9 globalmente, e então monitorar incidentes e reativar a revisão se os defeitos de produção aumentarem.",
            "D": "Detalhar os resultados de validação por categoria de artefato e campo gerado, e então reduzir a revisão apenas para segmentos consistentemente confiáveis."
        }
    }
}

template = """Scenario: {question}

---

[ ] A - {opt_A}
[ ] B - {opt_B}
[ ] C - {opt_C}
[ ] D - {opt_D}

---

### TRANSLATED QUESTION
{trans_q}
Alternativas traduzidas:

A) {trans_opt_A}
B) {trans_opt_B}
C) {trans_opt_C}
D) {trans_opt_D}

---

### EXPLANATION (TECH LEAD)

Explicação:
{tech_exp}

---

### 🚸 CHILDREN EXPLANATION

Explicação:
{child_exp}

---

### CORRECT ANSWER

[ ] {correct} - {correct_opt_text}
"""

for card in cards:
    num = card['num']
    if num not in data:
        continue
    
    q = card['question'].replace("Scenario: ", "").strip()
    opts = card['options']
    
    d = data[num]
    trans_opts = d['opt_trans']
    
    correct_letter = d['correct']
    correct_opt_text = opts.get(correct_letter, opts.get(correct_letter.upper(), ""))
    
    content = template.format(
        question=q,
        opt_A=opts.get('A', ''),
        opt_B=opts.get('B', ''),
        opt_C=opts.get('C', ''),
        opt_D=opts.get('D', ''),
        trans_q=d['trans_q'],
        trans_opt_A=trans_opts['A'],
        trans_opt_B=trans_opts['B'],
        trans_opt_C=trans_opts['C'],
        trans_opt_D=trans_opts['D'],
        tech_exp=d['tech_exp'],
        child_exp=d['child_exp'],
        correct=correct_letter,
        correct_opt_text=correct_opt_text
    )
    
    file_path = os.path.join(out_dir, f"{num}-enriched-card.md")
    with open(file_path, "w", encoding="utf-8") as out_f:
        out_f.write(content)
    print(f"Generated {file_path}")

print("All done!")
